/**
 * Regenerates `src/i18n/generated/resources.d.ts` from the reference locale so
 * `t('users:USER_NOT_FOUND')` is autocompleted and typo-checked.
 *
 * Run: `bun run i18n:gen-types`
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const i18nRoot = path.resolve(here, '..');
const projectRoot = path.resolve(i18nRoot, '..', '..');

const REFERENCE_LOCALE = 'en';
const localeDir = path.join(i18nRoot, 'locales', REFERENCE_LOCALE);
const outFile = path.join(i18nRoot, 'generated', 'resources.d.ts');

const namespaces: Record<string, unknown> = {};
for (const file of readdirSync(localeDir).sort()) {
	if (!file.endsWith('.json')) continue;
	const ns = file.replace(/\.json$/, '');
	namespaces[ns] = JSON.parse(readFileSync(path.join(localeDir, file), 'utf8'));
}

const content = `// Generated by src/i18n/scripts/gen-types.ts — do not edit.
interface Resources ${JSON.stringify(namespaces, null, 2)}

export default Resources;
`;

mkdirSync(path.dirname(outFile), { recursive: true });
writeFileSync(outFile, content);
console.log(`wrote ${path.relative(projectRoot, outFile)}`);
